// <auto-generated />
namespace UniversityInformationSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CourseNameLengthChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CourseNameLengthChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201704171440472_CourseNameLengthChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
